config/routes.rb
Sifin::Application.routes.draw do
  resources :roles
  resources :user_sessions
  
  resources :users do
    collection do
      get :change_password
    end
  end
     
  resource :user, :as => 'account'  # a convenience route
  
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => 'users#new', :as => :signup

  root :to => 'user_sessions#new'

end

app/models/user_session.rb
class UserSession <  Authlogic::Session::Base
  #attr_accessible :data, :session_id
   self.logout_on_timeout = true

	def to_key
	  new_record? ? nil : [ self.send(self.class.primary_key) ]
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user, :only => :destroy
  layout 'login'

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])    
    if @user_session.save
      flash[:notice] = "1Inicio de sesion exitoso!"
      redirect_back_or_default account_url(@current_user)
    else
      flash[:notice] = "4Usuario y/o contraseña invalidos."
      redirect_to login_url
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout exitoso!"
    redirect_back_or_default new_user_session_url
  end

=begin
# GET /user_sessions
  # GET /user_sessions.json
  def index
    @user_sessions = UserSession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_sessions }
    end
  end

  # GET /user_sessions/1
  # GET /user_sessions/1.json
  def show
    @user_session = UserSession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_session }
    end
  end

  # GET /user_sessions/new
  # GET /user_sessions/new.json
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_session }
    end
  end

  # GET /user_sessions/1/edit
  def edit
    @user_session = UserSession.find(params[:id])
  end

  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to @user_session, notice: 'User session was successfully created.' }
        format.json { render json: @user_session, status: :created, location: @user_session }
      else
        format.html { render action: "new" }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_sessions/1
  # PUT /user_sessions/1.json
  def update
    @user_session = UserSession.find(params[:id])

    respond_to do |format|
      if @user_session.update_attributes(params[:user_session])
        format.html { redirect_to @user_session, notice: 'User session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session = UserSession.find(params[:id])
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to user_sessions_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_id %><br />
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_area :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Session</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.session_id %></td>
    <td><%= user_session.data %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<div class="wrapper">  
  <%= form_for @user_session, :as => :user_session, :url => { :action => "create" }, :html => {:class => "login"} do |f| %>
    <center>
      <%= image_tag("logo_sifin.png")%>      
    </center>
    <p class="title"></p>
    <input type="text" name="user_session[login]" required="required" placeholder="Usuario" autofocus="true" 
    oninvalid="this.setCustomValidity('Ingresar el usuario.')" oninput="setCustomValidity('')"/>
    <i class="fa fa-user"></i>
    <input type="password" name="user_session[password]" required="required" placeholder="Contraseña" oninvalid="this.setCustomValidity('Ingresar la contraseña.')"
    oninput="setCustomValidity('')"/>
    <i class="fa fa-key"></i>
    <a href="#">Olvidaste tu contraseña?</a>
    <button>
      <i class="spinner"></i>
      <span class="state">LOGIN</span>
    </button>    
  <% end %>
</div>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Session:</b>
  <%= @user_session.session_id %>
</p>

<p>
  <b>Data:</b>
  <%= @user_session.data %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>